#+title: Batsignal
#+author: pspiagicw

  The improved version of batsignal (The battery monitor). The original project is [[https://github.com/electrickite/batsignal][here]].
  This is a simple battery monitor that provides notifications for battery events.

  This is intended to use with minimal window managers like XMonad , SpectreWM , qtile etc.

  It raises notification using the ~libnotify~ method (~notify-send~).This requires a
  notification daemon running in the background . A common one is ~dunst~

  Currently only Linux is supported.
  
** Usage
   Start batsignal using the command
   #+begin_src shell
batsignal
   #+end_src

   Start in the the background using
   #+begin_src sql
batsignal -b
   #+end_src

   Put it in your ~~/.xinitrc~ to autostart before your window manager.
   #+begin_src shell
# Battery Monitor
batsignal -b
#Window Manager
exec xmonad
   #+end_src

   See ~man batsignal~ for more details.
** Prerequisites
   The following software are needed to compile and build.
   - A standard C compiler
   - libnotify
   - make
   - pkg-config
     
** Installation
   Building the package is done using make.
   #+begin_src shell
make
   #+end_src


   This produces a ~batsignal~ binary. Either move this to a directory existing in $PATH. Or use ~sudo make install~
   to install in ~/usr/bin/~.

   #+begin_src shell
sudo make install
   #+end_src

   
** Features
   This fork adds multiple features like
   - Detecting whether battery is in charging , discharging .
   - Detect events like charging attach , charging removed.
   - Multiple Icons for different events.
   - Run custom commands at events (Low charge , Danger Charge , Charging connected).


** Configuration
   Configuration can be done using ~batsignal.c~ file. The file has variables that can be edited for custom configuration

   These can be edited for configuration. Remember to compile and install again when edited.
   #+begin_src C
static unsigned char daemonize = 0;
static unsigned char battery_required = 1;
static unsigned char battery_name_specified = 0;

/* battery information */
static char *battery_name = "BAT0";
static unsigned char battery_discharging = 0;
static unsigned char battery_state = STATE_AC;
static unsigned int battery_level = 100;
static char *attr_path;

/* check frequency multiplier (seconds) */
static unsigned int multiplier = 60;

/* battery warning levels */
static unsigned int warning = 15;
static unsigned int critical = 5;
static unsigned int danger = 2;
static unsigned int full = 75;

/* messages for battery levels */
static char *warningmsg = "Battery is low";
static char *criticalmsg = "Battery is critically low";
static char *fullmsg = "Battery is full";
static char *disconnectedmsg = "Charging Disconnected";
static char *connectedmsg = "Charging Connected";

static char *dangercmd = "";
static char *lowcmd = "xbackglight -set 20";
static char *connectedcmd = "xbacklight -set 40";

   #+end_src
   
** Contributing
   Pull requests are welcome. For features requests and bug reports open a [[https://github.com/pspiagicw/batsignal-improved/issues][issue]].
** Motivation
   This was my personal copy with my modifications on batsignal. I though of releasing it on GitHub and thus this project was born.
** License
   This project uses the [[https://opensource.org/licenses/MIT][MIT License]].

